config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}
  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  devise_for :users, controllers: {registrations: 'users/registrations'}
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/resources/edit.html.erb
<div id="new" class="edit">
<%= javascript_include_tag "new" %>
<%= javascript_include_tag "filter" %>

<div id="suggest_form">
    <div id="edit-top">
        <div id="edit-title" %>
            <h1>Edit: <%= @resource.title%></h1>
        </div>
        <div class="links" %>
            <%= link_to("View Resource", "/resources/" + @resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
        </div>
    </div>

  <%= form_tag("/resources/" + @resource.id.to_s + ".html", method: "patch", id: "form_section") do %>
      <div class="form_step" id="contact_info">
          <h2>Contact info for person maintaining resource (not public facing)</h2>
          <div class="contact_row">
              <div class="input_field col">
                  <%= label_tag(:contact_email, "Contact Email", class: "required") %>
                  <p> Email for the contact person above to be sent requests to update resource information. </p>
                  <%= text_field_tag(:contact_email, nil, class: "required_input validate-input") %>
                    <p id="email-valid" class="invalid-text"> Invalid Email </p>
              </div>
              <div class="input_field col">
                  <%= label_tag(:contact_name, "Contact Name") %>
                  <p> A specific person who can speak for the organization and keep the resource information updated? </p>
                  <%= text_field_tag(:contact_name, @resource.contact_name) %>
              </div>
              <div class="input_field col">
                  <%= label_tag(:contact_phone, "Contact Phone") %>
                  <p> What number can we call if we have a question about the resource? </p>
                  <%= text_field_tag(:contact_phone, nil, class: "validate-input") %>
                    <p id="phone-valid" class="invalid-text"> Invalid Phone </p>

              </div>
          </div>

          
      </div>

      <div class="form_step">
          <h2>Basic information about the resource</h2>
          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:title, "Resource name", class: "required") %>
                  <p> Title of the resource </p>
                  <%= text_field_tag(:title, @resource.title, class: "required_input") %>
              </div>
              <div class="input_field">
                  <%= label_tag(:url, "Resource URL", class: "required") %>
                  <p> Webpage for resource </p>
                  <%= text_field_tag(:url, @resource.url, class: "required_input") %>
              </div>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:desc, "Resource Description", class: "required") %>
                  <%= text_area_tag(:desc, @resource.desc, class: "required_input") %>
              </div>
          </div>

          <div class="resource_row association_row">
              <% @locations.each do |association, values| %>
                  <div id="location">
                      <%= label_tag(:location, association.capitalize, class: "required")%>
                  </div>
                  <div class="resource_checkboxes">
                      <% values.each do |val| %>
                            <div class="single_checkbox">
                                <% if @resource.location == val%>
                                    <div class="label loc-radio">
                                    <%= val %>
                                        <%= radio_button_tag association, val, true, class: "radio", id: val %>
                                    </div>
                                <% else %>
                                    <div class="label loc-radio">
                                        <%= val %>
                                        <%= radio_button_tag association, val, false, class: "radio", id: val %>
                                    </div>
                                <% end %>
                            </div>
                      <% end %>
                  </div>
              <% end %>
              <div id="other_location">
                  <p>Other: </p>
                  <%= text_field_tag(:other) %>
              </div>
          </div>

          <% @has_many_hash.each do |association, values| %>
              <% if (association ==  "types" || association == "audiences")%>
                  <div class="association_row">
                      <div class="association">
                          <%= label_tag(:association, association.capitalize, class: "required") %>
                      </div>
                      <div class="resource_checkboxes">
                          <% values.each do |val| %>
                                <div class="single_checkbox type_checkbox">
                                <% if @resource.send(association).collect(&:val).include?(val)%>
                                    <div class="label"><%= val %></div>
                                        <%= check_box_tag association+'[]', val, true, class: "checkbox", id: val %>
                                    </div>
                                <% else %>
                                    <div class="label"><%= val %></div>
                                        <%= check_box_tag association+'[]', val, false, class: "checkbox", id: val %>
                                    </div>
                                <% end %>
                          <% end %>
                      </div>
                  </div>
              <% end %>
          <% end %>
      </div>
      

      <div class="form_step">
          <h2>Other information about the resource</h2>

          <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:resource_email, "Email - General") %>
                    <p class="label-desc-other">Email associated with this resource. </p>
                    <%= text_field_tag(:resource_email, @resource.resource_email) %>
                </div>
                <div class="input_field col">
                    <%= label_tag(:resource_phone, "Phone - General") %>
                    <p class="label-desc-other">Phone associated with this resource. </p>
                    <%= text_field_tag(:resource_phone, @resource.resource_phone) %>
                </div>
                <div class="input_field col">
                    <%= label_tag(:address, "Address") %>
                    <p class="label-desc-other">Useful if you host events at your physical location. </p>
                    <%= text_field_tag(:address, @resource.address) %>
                </div>
            </div>

            <div class="resource_row">
                <div class="input_field other-info">
                    <%= label_tag(:deadline, "Deadline") %>
                    <p> What is the specific date applications are due or an event is held, or resource is available until? The first or upcoming deadline. </p>
                    <% if @resource.deadline != nil %>
                        <%= date_field_tag(:deadline, @resource.deadline.to_date()) %>
                    <% else %>
                        <%= date_field_tag(:deadline, nil) %>
                    <% end %>
                </div>
            </div>

          <div class="association_row">
              <% @has_many_hash.each do |association, values| %>
                  <% if (association !=  "types" && association != "audiences")%>
                      <div class="association">
                          <%= label_tag(:association, association.capitalize.gsub(/[^0-9A-Za-z,\s]/, " ")) %>
                      </div>
                      <div class="resource_checkboxes">
                      <% values.each do |val| %>
                        <div class="single_checkbox type_checkbox">
                        <% if @resource.send(association).collect(&:val).include?(val)%>
                            <div class="label"><%= val %></div>
                                <%= check_box_tag association+'[]', val, true, class: "checkbox", id: val %>
                            </div>
                        <% else %>
                            <div class="label"><%= val %></div>
                                <%= check_box_tag association+'[]', val, false, class: "checkbox", id: val %>
                            </div>
                        <% end %>
                  <% end %>
                      </div>
                  <% end %>
              <% end %>
          </div>

          <div class="resource_row">
              <div class="input_field">
                  <%= label_tag(:notes, "Notes") %>
                  <p> Note any other details on eligibility, deadlines, and process. </p>
                  <%= text_area_tag(:notes, @resource.notes) %>
              </div>
          </div>
      </div>

      <div id="form_submit">
          <%= submit_tag("Update", :id => "submit_button") %>
          <p id="message"> Description was too long. <p>
      </div>

  <% end %>
</div>
</div>

app/views/resources/index.html.erb
<div class="top" id="resources-index">
    <h1>Resources </h1>
</div>

<%= javascript_include_tag "filter" %>

<div class="index"  id="resource-container-wrapper">
  <div id="filter-column">
    <%= form_tag("/resources.html", method: :get) do %>
      
      <div class="row">
        <div id="filter-header">
          <%= submit_tag 'Filter', class: 'btn btn-outline-dark btn-lg', id: 'filter-button'%>
        </div>
      </div>

      <% @has_many_hash.each do |association, values| %>
        <div class="association">
          <h2><%= association.capitalize.gsub(/[^0-9A-Za-z,\s]/, " ") %></h2>
          <div class="filters">
            <% values.each do |val| %>
              <div class="single_checkbox gold_label">
                <div class="label"><%= val %></div>
                <%= check_box_tag association+'[]', val %>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <div id="resource-column">
    <div class="row">
      <div class="col-12" id = "result-header">
        <h2>Results</h2>
      </div>
    </div>
    <div class="row" id="pages">
      <ul class="pagination">
        <li class="page-arrow prev disabled" id="prev">
          <p id="prevLink" class="page-link prevLink">Previous</p>
        </li>
      </ul>
    </div>
    <% @resources.each do |resource| %>
      <div class="row resource-container">
        <div class="resource-title text">
          <%= link_to(resource.title, "/resources/" + resource.id.to_s + ".html") %>
        </div>
        <div class="resource-url text">
          URL: <a href="<%= resource.url %>"><%= resource.url %></a>
        </div>
        <div class="resource-desc text">
          Description: <%= resource.desc %>
        </div>
        <div class="resource-location text">
          Location: <%= resource.location %>
        </div>
        <div class="resource-types text">
          Types: <%= resource.types.collect(&:val).to_s.gsub(/[^0-9A-Za-z,\s]/, "") %>
        </div>
        <div class="resource-types text">
          Audiences: <%= resource.audiences.collect(&:val).to_s.gsub(/[^0-9A-Za-z,\s]/, "") %>
        </div>

       
        <div class="text links" %>
          <%= link_to("More info", "/resources/" + resource.id.to_s + ".html", class: "btn btn-outline-primary") %>
          <% if user_signed_in? %>
            <%= link_to('Edit', edit_resource_path(resource), class: "btn btn-outline-primary") %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row" id="pages">
      <ul class="pagination">
        <li class="page-arrow prev disabled" id="prev">
          <p id="prevLink" class="page-link prevLink">Previous</p>
        </li>
      </ul>
    </div>
    
  </div>
</div>

app/views/resources/new.html.erb
<div id="new">
<div class="top">
    <h1>Suggest a Resource for our Database </h1>
</div>

<%= javascript_include_tag "new" %>
<%= javascript_include_tag "filter" %>

<div id="instructions">
    <p>Fill out the form below to help contribute. We will contact you if we find the resource acceptable. If you are an Admin, the resource will automatically be approved.<p>
    <p class="required">Required fields are marked with an <p>
</div>

<div id="suggest_form">

    <%= form_tag("/resources.html", method: "post", id: "form_section") do %>
        <div class="form_step" id="contact_info">
            <h2>Contact info for person maintaining resource (not public facing)</h2>
            <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:contact_email, "Contact Email", class: "required") %>
                    <p class="label-desc"> Email for the contact person above to be sent requests to update resource information. </p>
                    <%= text_field_tag(:contact_email, nil, class: "required_input validate-input") %>
                    <p id="email-valid" class="invalid-text"> Invalid Email </p>
                </div>
                <div class="input_field col">
                    <%= label_tag(:contact_name, "Contact Name") %>
                    <p class="label-desc"> A specific person who can speak for the organization and keep the resource information updated? </p>
                    <%= text_field_tag(:contact_name) %>
                </div>
                <div class="input_field col">
                    <%= label_tag(:contact_phone, "Contact Phone") %>
                    <p class="label-desc"> What number can we call if we have a question about the resource? </p>
                    <%= text_field_tag(:contact_phone, nil, class: "validate-input") %>
                    <p id="phone-valid" class="invalid-text"> Invalid Phone </p>
                </div>
            </div>

            
        </div>

        <div class="form_step">
            <h2>Basic information about the resource</h2>
            <div class="resource_row">
                <div class="input_field">
                    <%= label_tag(:title, "Resource name", class: "required") %>
                    <p> Title of the resource </p>
                    <%= text_field_tag(:title, nil, class: "required_input") %>
                </div>
                <div class="input_field">
                    <%= label_tag(:url, "Resource URL", class: "required") %>
                    <p> Webpage for resource </p>
                    <%= text_field_tag(:url, nil, class: "required_input") %>
                </div>
            </div>

            <div class="resource_row">
                <div class="input_field">
                    <%= label_tag(:desc, "Resource Description", class: "required") %>
                    <%= text_area_tag(:desc, nil, class: "required_input") %>
                </div>
            </div>

            <div class="resource_row association_row">
                <% @locations.each do |association, values| %>
                    <div id="location">
                        <%= label_tag(:location, association.capitalize, class: "required")%>
                    </div>
                    <div class="resource_checkboxes">
                        <% values.each do |val| %>
                            <div class="single_checkbox">
                                <div class="label loc-radio"><%= val %></div>
                                <%= radio_button_tag association, val, false, class: "radio", id: val %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <div id="other_location">
                    <p>Other: </p>
                    <%= text_field_tag(:other) %>
                </div>
            </div>

            <% @has_many_hash.each do |association, values| %>
                <% if (association ==  "types" || association == "audiences")%>
                    <div class="association_row">
                        <div class="association">
                            <%= label_tag(:association, association.capitalize, class: "required") %>
                        </div>
                        <div class="resource_checkboxes">
                            <% values.each do |val| %>
                                <div class="single_checkbox type_checkbox">
                                <div class="label"><%= val %></div>
                                    <%= check_box_tag association+'[]', val, false, class: "checkbox", id: val %>

                                </div>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            <% end %>
        </div>

        <div class="form_step">
            <h2>Other information about the resource</h2>

            <div class="contact_row">
                <div class="input_field col">
                    <%= label_tag(:resource_email, "Email - General") %>
                    <p class="label-desc-other">Email associated with this resource. </p>
                    <%= text_field_tag(:resource_email, nil) %>
                </div>
                <div class="input_field col">
                    <%= label_tag(:resource_phone, "Phone - General") %>
                    <p class="label-desc-other">Phone associated with this resource. </p>
                    <%= text_field_tag(:resource_phone, nil) %>
                </div>
                <div class="input_field col">
                    <%= label_tag(:address, "Address") %>
                    <p class="label-desc-other">Useful if you host events at your physical location. </p>
                    <%= text_field_tag(:address, nil) %>
                </div>
            </div>

            <div class="resource_row">
                <div class="input_field other-info">
                    <%= label_tag(:deadline, "Deadline") %>
                    <p> What is the specific date applications are due or an event is held, or resource is available until? The first or upcoming deadline. </p>
                    <%= date_field_tag(:deadline, nil) %>

                </div>
            </div>

            

            <div class="association_row">
                <% @has_many_hash.each do |association, values| %>
                    <% if (association !=  "types" && association != "audiences")%>
                        <div class="association">
                            <%= label_tag(:association, association.capitalize.gsub(/[^0-9A-Za-z,\s]/, " ")) %>
                        </div>
                        <div class="resource_checkboxes">
                            <% values.each do |val| %>
                                <div class="single_checkbox">
                                    <div class="label"><%= val %></div>
                                    <%= check_box_tag association+'[]', val, false, class: "checkbox" %>
                                </div>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
            </div>

            <div class="resource_row">
                <div class="input_field">
                    <%= label_tag(:notes, "Notes") %>
                    <p> Note any other details on eligibility, deadlines, and process. </p>
                    <%= text_area_tag(:notes) %>

                </div>
            </div>
        </div>

        <div id="form_submit">
            <%= submit_tag("Submit", :id => "submit_button") %>
            <p id="message"> Description was too long. <p>
        </div>

    <% end %>
</div>
</div>

app/views/resources/show.html.erb
<div id="show">

<div id="show-title">
    <h2><%= @resource.title %></h2>
</div>

<div class="links" %>
    <%= link_to("Back", "/resources.html/" , class: "btn btn-outline-primary") %>
    <% if user_signed_in? %>
        <%= link_to('Edit', edit_resource_path(@resource), class: "btn btn-outline-primary") %>
        <% all_values = @all_values_hash %>
    <% else %>
        <% all_values = @all_public_values_hash %>
    <% end %> 
</div>

<div id="resource_info">
    <% i = 0 %>
    <% all_values.map do |key, value| %>
        <% text = @resource[value]%>
        <% if (@has_many_hash.key?(value)) %>
            <% text = @resource.send(value).collect(&:val) %>
            <% text = text.to_s.gsub(/[^0-9A-Za-z,\s]/, "") %>
        <% end %>
        <% if (text != nil && text.to_s.length != 0) %>
            <% if (i % 2 === 1) %>
                <div class="text colored">
            <% else %>
                <div class="text">
            <% end %>
                <p>
                    <b><%= key.to_s + ": "%></b> 
                    <% if (key.to_s === "URL") %>
                        <a href="<%= text.to_s %>"><%= text.to_s %></a>
                    <% elsif (key.to_s === "Deadline") %>
                        <%= text.to_s.to_date() %>
                    <% else %>
                        <%= text.to_s %>
                    <% end %>
                </p>
            </div>
            <% i += 1 %>
        <% end %>
        
    <% end %>
</div>



</div>

app/views/resources/unapproved.html.erb
<div class="top" id="approval-title">
  <h1>Approval Queue</h1>
</div>

<%= javascript_include_tag "unapproved" %>

<div id="unapproved"  id="resource-container-wrapper">
    <div class="col" id="approval-column">
      <%= form_tag("/resources/approve/many.html", method: :post) do %>
        <div id="result-header">
          <%= @resource_count %> awaiting approval
          <%= submit_tag 'Approve selected resources', class: 'btn btn-outline-dark approve-button' %>
          <form action=<%=resources_approve_many_path %>, method="post">
            <button class='btn btn-outline-dark' id="approve-all-button" name="approve_list" value="all">
              Approve All
            </button>
          </form>
        </div>
        
        
      <% @resources.each do |resource| %>
        <div class="row resource-container unapproved-resource">
            <div class="resource-title text">
                <%= resource.title %>
            </div>
            <div class="approval-checkbox">
              <%= check_box_tag 'approve_list[]', resource.id, checked=false %>
            </div>

            <div>
              <% i = 0 %>
              <% @all_values_hash.map do |key, value| %>
                  <% text = resource[value]%>
                  <% if (@has_many_hash.key?(value)) %>
                      <% text = resource.send(value).collect(&:val) %>
                      <% text = text.to_s.gsub(/[^0-9A-Za-z,\s]/, "") %>
                  <% end %>
                  <% if (text != nil && text.to_s.length != 0) %>
                      <% if (i % 2 == 1) %>
                          <div class="text colored">
                      <% else %>
                          <div class="text">
                      <% end %>
                          <p><b><%= key.to_s + ": "%></b> <%= text.to_s %></p>
                      </div>
                      <% i += 1 %>
                  <% end %>
                  
              <% end %>
          </div>
        </div>
      <% end %>
      <% end %>
  </div>
  
</div>