config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}
  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  devise_for :users, controllers: {registrations: 'users/registrations'}
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bug_report.rb
class BugReport < ApplicationRecord

end

app/controllers/bug_reports_controller.rb
class BugReportsController < ApplicationController
  before_action :set_bug_report, only: [:show, :edit, :update, :destroy]
  before_action :access_control, only: [:index, :show, :edit, :update, :destroy]

  # GET /bug_reports
  # GET /bug_reports.json
  def index
    @bug_reports = BugReport.all
  end

  # GET /bug_reports/1
  # GET /bug_reports/1.json
  def show
    @bug_report = BugReport.find(params[:id])
  end

  # GET /bug_reports/new
  def new
    @bug_report = BugReport.new
  end

  # GET /bug_reports/1/edit
  def edit

  end

  # POST /bug_reports
  # POST /bug_reports.json
  def create
    @bug_report = BugReport.new(bug_report_params)

    respond_to do |format|
      if @bug_report.save
        format.html { redirect_to @bug_report, notice: 'Bug report was successfully created.' }
        format.json { render :show, status: :created, location: @bug_report }
      else
        format.html { render :new }
        format.json { render json: @bug_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bug_reports/1
  # PATCH/PUT /bug_reports/1.json
  def update
    respond_to do |format|
      if @bug_report.update(bug_report_params)
        format.html { redirect_to @bug_report, notice: 'Bug report was successfully updated.' }
        format.json { render :show, status: :ok, location: @bug_report }
      else
        format.html { render :edit }
        format.json { render json: @bug_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bug_reports/1
  # DELETE /bug_reports/1.json
  def destroy
    @bug_report.destroy
    respond_to do |format|
      format.html { redirect_to bug_reports_url, notice: 'Bug report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug_report
      @bug_report = BugReport.find(params[:id])
    end

    def access_control
      if !user_signed_in?
        flash[:alert] = "You must be logged in to access this page"
        redirect_to welcome_index_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_report_params
      params.require(:bug_report).permit(:desc, :closed)
    end
end

app/helpers/bug_reports_helper.rb
module BugReportsHelper
end

app/helpers/bugreports_helper.rb
module BugreportsHelper
end

app/views/bug_reports/_form.html.erb
<%= form_with(model: bug_report, local: true) do |form| %>
  <% if bug_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bug_report.errors.count, "error") %> prohibited this bug_report from being saved:</h2>

      <ul>
      <% bug_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :desc %>
    <br/>
    <%= form.text_field :desc %>
  </div>

  <div class="field">
    <%= form.label :closed %>
    <br/>
    <%= form.check_box :closed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/bug_reports/edit.html.erb
<h1>Editing Bug Report</h1>

<%= render 'form', bug_report: @bug_report %>

<%= link_to 'Show', @bug_report %> |
<%= link_to 'Back', bug_reports_path %>

app/views/bug_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="title">Bug Reports</h1>

<br/>

<div class= "container" id="bug-report-container">
  <% @bug_reports.each do |bug_report| %>
    <% unless bug_report.closed %>
      <div class="row bug-report-description">
        <%= bug_report.desc %>
      </div>
    <% end %>
  <% end %>
  <%= link_to 'New Bug Report', new_bug_report_path %>
</div>

app/views/bug_reports/new.html.erb
<h1>New Bug Report</h1>

<%= render 'form', bug_report: @bug_report %>

<%= link_to 'Back', bug_reports_path %>

app/views/bug_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @bug_report.desc %>
</p>

<p>
  <strong>Closed:</strong>
  <%= @bug_report.closed %>
</p>

<%= link_to 'Edit', edit_bug_report_path(@bug_report) %> |
<%= link_to 'Back', bug_reports_path %>