config/routes.rb
Rails.application.routes.draw do
  resources :bug_reports
  get 'faq/index'
  get 'welcome/index'
  get 'resources/unapproved', to: 'resources#unapproved'
  # If a 'display user information' page gets added, may be good idea to move location
  # of flash key button to that page.
  devise_scope :user do
    get 'user/showkey', to: 'users/registrations#showkey', as: 'showkey_user'
  end
  resources :resources, :defaults => {:format => 'json'}
  match 'resources/approve/many' => 'resources#approve_many', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  match 'resources/approve/:id' => 'resources#update', via: [:put, :patch, :post], :defaults => {:format => 'json'}
  root "welcome#index"
  devise_for :users, controllers: {registrations: 'users/registrations'}
  #For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <nav class="navbar">
      <div id="left-nav">
        <a class="btn btn-primary nav-link nav-item" href="/">Home</a>
        <a class="btn btn-info nav-link nav-item" href="/resources.html/">All Resources</a>
        <a class="btn btn-info nav-link nav-item" href="/resources/new.html">Suggest a Resource</a>
        <% if user_signed_in? %>
          <a class="btn btn-info nav-link nav-item" href="/resources/unapproved.html">Approval Queue</a>
        <% end %>
        <a class="btn btn-info nav-link nav-item" href="/faq/index.html">FAQ</a>     
      </div>
      <div id="right-nav">
        <%= link_to('Submit a Bug Report', new_bug_report_path, method: :get, class: 'btn btn-success admin-button') %>
        <% if user_signed_in? %>
          <%= link_to('See Bug Reports', bug_reports_path, method: :get, class: 'btn btn-success admin-button') %>
          <%= link_to('Edit Account', edit_user_registration_path, method: :get, class: 'btn btn-success admin-button') %>
          <%= link_to('View API Key', showkey_user_path, method: :get, class: 'btn btn-success admin-button') %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'btn btn-warning admin-button') %>
        <% else %>
          <%= link_to('Admin Login', new_user_session_path, class: 'btn btn-success admin-button')  %>
          <%= link_to('Admin Registration', new_user_registration_path, class: 'btn btn-success admin-button') %>
        <% end %>
      </div>
    </nav>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>


</html>